#pragma once

/* Pins */
#define PIN_HEARTBEAT_SENSOR ADC2_CHANNEL_5 // 12
#define PIN_ACCELEROMETER_SDA 17
#define PIN_ACCELEREMOTER_SCL 16
#define PIN_CHARGING_INPUT ADC2_CHANNEL_8 // 25
#define PIN_CONNECT_LED 23
#define PIN_BOARD_LED 22

/* Heartbeat data */
#define HEARTBEAT_THRESHOLD 90
#define HEARTBEAT_MIN_LENGTH 3
#define HEARTBEAT_MAX_PEAK_LENGTH 3

/* Heartbeat sensor */
#define HEARTBEAT_SAMPLING_TIME 8000
#define HEARTBEAT_SAMPLING_DELAY 30
#define HEARTBEAT_SAMPLE_LENGTH HEARTBEAT_SAMPLING_TIME / HEARTBEAT_SAMPLING_DELAY

/* Accelerometer data */
#define ACCELEROMETER_STEPS_THRESHOLD 2600
#define ACCELEROMETER_STEPS_SHAKE_THRESHOLD 42
#define ACCELEROMETER_SHAKE_THRESHOLD 500
#define ACCELEROMETER_FALL_THRESHOLD 46000

/* Accelerometer sensor */
#define ACCELEROMETER_SAMPLING_TIME 2000
#define ACCELEROMETER_SAMPLING_DELAY 20
#define ACCELEROMETER_SAMPLE_LENGTH ACCELEROMETER_SAMPLING_TIME / ACCELEROMETER_SAMPLING_DELAY

/* Misc */
#define CHARGING_THRESHOLD 3600
