#pragma once

/* Pins */
#define PIN_HEARTBEAT_SENSOR A0
#define PIN_VIBRATION_MODULE 5

/* Heartbeat data */
#define HEARTBEAT_THRESHOLD 128
#define HEARTBEAT_MIN_LENGTH 3
#define HEARTBEAT_MAX_PEAK_LENGTH 3

/* Heartbeat sensor */
#define HEARTBEAT_SAMPLING_TIME 16000
#define HEARTBEAT_SAMPLING_DELAY 30
#define HEARTBEAT_SAMPLE_LENGTH HEARTBEAT_SAMPLING_TIME / HEARTBEAT_SAMPLING_DELAY

/* Accelerometer sensor */
#define ACCELEROMETER_SAMPLING_TIME 1000
#define ACCELEROMETER_SAMPLING_DELAY 10
#define ACCELEROMETER_SAMPLING_LENGTH ACCELEROMETER_SAMPLING_TIME / ACCELEROMETER_SAMPLING_DELAY
